language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    # per travis-ci issue #5036, add '-tools' to use build-tools-23.0.2
    - tools
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components go here.

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests

script: ./gradlew test
