language: android

# Required to run retrolambda
jdk:
    - oraclejdk8
    
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    # per travis-ci issue #5036, add '-tools' to use build-tools-23.0.2
    - tools
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests

before_script:
  # Tests crash if a local.properties file isn't present; this file is not kept
  # under version control. Create an empty local.properties for testing.
  - touch local.properties

script: ./gradlew test

# Uncomment line below to add post-test scripts.
# after_script:
#   - cat /home/travis/build/nrlakin/ResearchStack/backbone/build/reports/tests/debug/classes/org.researchstack.backbone.task.TaskTest.html
